config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'user/registrations' }

  root to: "group#index"

  resources :user do 
    resources :movement, only: [:new, :create]
    get '/movement/new_move' => 'movement#new_mov'
    resources :group, only: [:index, :new, :create, :show, :destroy] do
      resources :movement, only: [:index, :new, :create, :show, :destroy]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user_id, presence: true
  validates :amount, presence: true
  validates :group_id, presence: true
end

app/controllers/movement_controller.rb
class MovementController < ApplicationController
  def new
    @movement = Movement.new
    @group = params[:group_id]
  end

  def new_mov
    @movement = Movement.new
    @groups = Group.where(user_id: current_user.id)
  end

  def create
    if params[:group_id]
      @group = Group.find(params[:group_id])
      @movement = @group.movements.build(movement_params)
      @movement.user = @group.user
    else
      @movement = current_user.movements.build(movement_params)
      @group = Group.where(user_id: current_user.id)
    end
    if @movement.save
      if params[:group_id]
        redirect_to user_group_path(current_user.id, @group), notice: 'Movement was successfully added.'
      else
        redirect_to user_group_index_path(current_user.id), notice: 'Movement was successfully added.'
      end
    else
      puts 'error'
    end
  end

  def index
    @movements = Movement.includes(:groups).where(user_id: params[:user_id], group_id: params[:group_id])
    @group = Group.includes(:movements).find(params[:group_id])
    @total = @group.movements.sum(:amount)
  end

  def destroy
    @movement = Movement.find(params[:id])
    @movement.destroy
    redirect_to user_group_path(current_user.id, @movement.group.id), notice: 'Movement was successfully deleted.'
  end

  private

  def movement_params
    params.require(:movement).permit(:name, :amount, :group_id)
  end
end

app/helpers/movement_helper.rb
module MovementHelper
end

app/views/movement/index.html.erb
<h1> testing index <h1>

<% @movements.map do |movement| %>
<%= movement.id %></br>
<%= movement.user.name %></br>
<%= movement.name %></br>
<%= movement.amount %></br>
<% end %>
<%= @total %>

app/views/movement/new.html.erb
<style>
  .shared-header-cont{display:none;}
  .wrapper {padding: 0}
  .shared-back {transform: translateY(0px) !important;}
  @media (max-width: 625px) {
    .data-form-cont{ flex-direction: column-reverse; }
  }
  .shared-back {
  background-color: #e47921;
  color: white;
  padding: 0.2rem 0.5rem 0.2rem;
  border-radius: 5px;
  transform: translateY(0.5rem);
  transition: all 0.15s ease-in-out;
  text-transform: capitalize;
  border: 1px solid black;
}
.shared-back:hover {
  background-color: #ff953e;
  transform: scale(1.05) translateY(0.5rem);
}
</style>
<div class="data-form-cont">
  <div class="form-image", style="background-image: url('<%= asset_path 'addMov.svg' %>');"></div>
  <%= form_with(model: @movement, url: user_group_movement_index_path(user_id: current_user.id, group_id: @group), local: true, data:{turbo: false}, method: :post, class:'data-form') do |form| %>
    <h1 class="form-title">add new movement</h1>
    <!-- Form fields here -->

    <div class="form-inputs">
    <%= form.text_field :name, placeholder: 'Transaction Name', class: 'form-input', required: true %>
    <%= form.number_field :amount, placeholder: 'Amount', class: 'form-input', required: true %>
</div>

    <% if @movement.errors.any? %>
      <% @movement.errors.full_messages.each do |msg| %>
        <div class="error-messages"> 
          <p class="error-text"><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    <%= form.submit class:'form-submit' %>
        <div class="form-buttons">
<%= link_to "go back", user_group_path(current_user.id, @group), data:{turbo:false}, class:'shared-back' %>
    </div>
  <% end %>
   
</div>

app/views/movement/new_mov.html.erb
<style>
  .shared-header-cont{display:none;}
  .wrapper {padding: 0}
  .shared-back {transform: translateY(0px) !important;}
  @media (max-width: 625px) {
    .data-form-cont{ flex-direction: column-reverse; }
  }
</style>
<div class="data-form-cont">
  <div class="form-image", style="background-image: url('<%= asset_path 'addMov.svg' %>');"></div>
  <%= form_with(model: @movement, url: user_movement_index_path(user_id: current_user.id), local: true, data:{turbo: false}, method: :post, class:'data-form') do |form| %>
    <h1 class="form-title">add new movement</h1>
    <!-- Form fields here -->
    <div class="form-inputs">
      <%= form.text_field :name, placeholder: 'Transaction Name', class: 'form-input', required: true %>
      <%= form.number_field :amount, placeholder: 'Amount', class: 'form-input', required: true %>
      <%= form.collection_select(:group_id, @groups, :id, :name, {include_blank: "select group"}, class:'form-input group-select', required: true) %>
    </div>
    <% if @movement.errors.any? %>
      <% @movement.errors.full_messages.each do |msg| %>
        <div class="error-messages">
          <p class="error-text"><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    <%= form.submit class:'form-submit' %>
    <div class="form-buttons">
      <%= render "/shared/buttons" %>
    </div>
  <% end %>
</div>