config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'user/registrations' }

  root to: "group#index"

  resources :user do 
    resources :movement, only: [:new, :create]
    get '/movement/new_move' => 'movement#new_mov'
    resources :group, only: [:index, :new, :create, :show, :destroy] do
      resources :movement, only: [:index, :new, :create, :show, :destroy]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :movements, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  load_and_authorize_resource
  def index
    return unless user_signed_in?

    @groups = Group.where(user_id: current_user.id)
  end

  def new
    @group = Group.new
    @icons = UserIcons::GROUPICONS
  end

  def show
    @group = Group.order(created_at: :desc).find(params[:id])
  end

  def create
    @icons = UserIcons::GROUPICONS
    @group = current_user.groups.build(group_params) # Associate the group with the current user
    if @group.save
      redirect_to user_group_index_path(current_user.id), notice: 'Group was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    @group = Group.find(params[:id])

    @group.destroy
    redirect_to '/', notice: 'Group was successfully deleted.'
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/group/index.html.erb
<% stylesheet_link_tag 'group-index' %>
<div class="group-index-cont">
  <% if user_signed_in? %>
    <div class="group-index-header">
      <h1 class="group-index-title">WiseWallet</h1>
    </div>
    <style>
      .wrapper {padding: 0}
      .group-index-cont {justify-content: flex-start; border-radius: 0; padding: 0.7rem; gap: 1rem;}
      .group-index-title {font-size: 2.5rem; transform: translateY(1rem)}
      @media (max-width: 500px) {
        .group-cont {box-shadow: none; width: 100dvw; height: 120%; border:none; border-radius: 0;}
        .group-actions { width: 100vw; justify-content: center; gap: 0;}
        .group-btn {width: 100vw; margin: 0; border-radius: 0;}
        .group-index-cont{gap:0;}
        .shared-back {margin-bottom: 1rem;}

      }
    </style>
    <div class="group-tags">
      <h3 class="group-tag-name">Groups information</h3>
    </div>
    <div class="group-cont">
      <style>
        .group-index-cont{
        background-image: url('<%= asset_path 'index-bg.svg' %>');
        background-position-Y: -2rem;
        background-position-x: -6rem;
        background-size: 131vw 31rem;
        }
        @media (max-width: 1024px) {

        .group-index-cont {
        background-size: 94rem 33rem;
        background-position-x: -31rem;
        }

        }
      </style>
      <% if @groups.any? %>
        <% @groups.each do |g| %>
          <div class="group-info">
            <%= link_to  user_group_path(current_user.id, g.id), class:'group-link' do %>
              <%= image_tag("group_icons/#{g.icon}", class:"group-image", alt:"group image" )%>
              <div class="group-data">
                <h3 class="group-name"> <%= g.name %> </h3>
                <p class="group-created"> <%= g.created_at.strftime("%B %d, %Y") %></p>
              </div>
            <% end %>
            <div class="group-total">
              <p class="group-movement-total">
                Total: $<%= number_with_delimiter(g.movements.sum(:amount), delimiter: '.', separator: ',') %>
              </p>
              <%= button_to 'Delete Group', user_group_path(current_user.id, g.id), method: :delete, data: {turbo_confirm: 'Delete group and its movements?'}, class:'group-delete' %>
            </div>
          </div>
        <% end %>
      <% else %>
        <style>
          .group-empty-cont {display: flex; flex-direction: column; justify-content: center; align-items: center; transform: translateY(-5rem); gap: 1rem;}
          .group-empty {color: grey; text-align: center;}
          .group-empty-link {margin:0.5rem;}
          .group-empty-link a {color: white; padding: 0.5rem 1rem; background-color: #f80; border-radius: 8px; font-weight: bold;}
          .group-cont {justify-content: center;}
        </style>
        <div class="group-empty-cont">
        <h2 class="group-empty">You don't have any group yet</h2>
        <p class="group-empty-link"><%= link_to "Add the first one", new_user_group_path(current_user.id), data:{turbo: false}%></p>
        </div>
      <% end %>
    </div>
  
    <% if @groups.any? %>
      <div class="group-actions">
        <%= link_to "New Group", new_user_group_path(current_user.id), data:{turbo: false}, class: "group-btn" %>
        <%= link_to "New Movement", user_movement_new_move_path(current_user.id), data:{turbo: false}, class: "group-btn" %>
      </div>
    <% end %>
  <% else %>
    <h1 class="group-index-title"> WiseWallet </h1>
    <style>
    .shared-back {  }
      .shared-header-cont{display: none;}
      .group-index-cont{max-width: 30rem}
      .group-index-cont::before{background-image: url('<%= asset_path 'waves.svg' %>');}
    </style>
    <h3 class="group-index-sub"> Control your financial management </br> With intelligent spending insights </h3>
  <div class="group-index-actions">
    <div class="btn-cont"><%= link_to "Register", new_user_registration_path, class: "group-index-button btn1" %></div>
    <div class="btn-cont"><%= link_to "Log In", new_user_session_path, class: "group-index-button btn2" %></div>
  </div>
  <div class="group-index-social">
    <h4> Find us: </h4>
    <div class="social-icons" >
      <a href="https://github.com/VelzckC0D3" target="_blank" rel="noopener noreferrer">
        <img src="<%= asset_path 'facebook-icon.svg' %>" alt="User Icon" class="index-icon">
      </a>
      <a href="https://github.com/VelzckC0D3" target="_blank" rel="noopener noreferrer">
        <img src="<%= asset_path 'instagram-icon.svg' %>" alt="User Icon" class="index-icon">
      </a>
      <a href="https://github.com/VelzckC0D3" target="_blank" rel="noopener noreferrer">
        <img src="<%= asset_path 'twitter-icon.svg' %>" alt="User Icon" class="index-icon">
      </a>
    </div>
  </div>
<% end %>
</div>

app/views/group/new.html.erb
<style>
  .shared-header-cont{display:none;}
  .wrapper { padding: 0 }
  .error-messages{
    background-color: transparent;
  }
  .shared-back {transform: translateY(0px) !important;}
  .error-text{
    background-color: #0000008a;
    color: white;
    padding: 0.25rem;
    border-radius: 6px;}
</style>
<div class="data-form-cont">
  <%= form_with(model: @group, url: user_group_index_path(current_user), local: true, data:{turbo: false}, class:'data-form') do |form| %>
    <h1 class="form-title">add new group</h1>
    <h4 class="form-pictures-label"> Pick an Image (scroll down for more options) </h4>
    <div class="pictures-wrapper">
      <% @icons.map do |i| %>
        <div class="pictures-cont">
          <%= form.radio_button :icon, i, class:'picture-checkbox', required: true %>
          <%= image_tag "group_icons/#{i}", class:'profile-picture' %>
        </div>
      <% end %>
    </div>
    <div class="form-inputs">
      <%= form.text_field :name, placeholder: 'Group Name', class: 'form-input' %>
    </div>
    <% if @group.errors.any? %>
      <% @group.errors.full_messages.each do |msg| %>
        <div class="error-messages">
          <p class="error-text"><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    <%= form.submit "Create Group", class:'form-submit' %>
    <div class="form-buttons">
      <%= render "/shared/buttons" %>
    </div>
  <% end %>
  <div class="form-image", style="background-image: url('<%= asset_path 'addGroup.svg' %>');"></div>
</div>

app/views/group/show.html.erb
<% stylesheet_link_tag 'group-show' %>
<style>
  .wrapper {padding: 0}
  .group-cont {padding: 3rem 1rem}
  .group-index-cont {justify-content: flex-start; border-radius: 0; padding: 2rem 0.7rem 1rem !important; gap: 0.25rem;}
  .group-index-title {font-size: 2.5rem; transform: translateY(1rem)}
</style>
<div class="group-index-cont">
  <%= image_tag("group_icons/#{@group.icon}", class:"group-image", alt:"group image" )%>
  <h1 class="movement-title"> <%= @group.name %> Movements </h1>
  <h3 class="movement-sub">Total: $<%= number_with_delimiter(@group.movements.sum(:amount), delimiter: '.', separator: ',') %></h3>
    <div class="movement-cont">
  <% if @group.movements.any? %>
      <% @group.movements.map do |m| %>
        <div class="group-info">
          <div class="movement-info">
            <h3> <%= m.name %> </h3>
            <p class="movement-date"> <%= m.created_at.strftime("%B %d, %Y %I:%M %p") %> </p>      
        </div>
        <div class="movement-info">
          <p> amount: $<%= number_with_delimiter(m.amount.to_i, delimiter: '.') %> </p>
          <%= button_to 'Delete transaction', user_group_movement_path(current_user.id, @group.id, m.id), class:'movement-delete', method: :delete, data: { turbo_confirm: 'Are you sure?' }%>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to 'New Movement', new_user_group_movement_path(current_user.id, @group.id), class:'movement-btn' %>

<style> 
.shared-back {transform: translateY(-0.4rem)} 
.shared-back:hover {transform: translateY(-0.4rem)}
.movement-btn {transform: translateY(-1rem)}
.movement-sub {margin-bottom: 2rem}
@media (max-width: 500px) {
.group-index-cont { padding: 1rem 0  0!important; }
.movement-btn { border-radius: 0;  transform: translateY(0.3rem); }
.movement-btn:hover { border-radius: 0;  transform: translateY(0.3rem); }
.shared-back {width: 100vw; text-align: center; height: 3rem; transform: translateY(0rem); padding: 1rem}
.shared-back:hover {width: 100vw; text-align: center; height: 3rem; transform: translateY(0rem); padding: 1rem}
.movement-cont {transform: translateY(0rem)}
}
</style>
</div>